[package]
name = "cli_01"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
ureq = "2.2.0"
postgres = "0.19.1"
pp_lib = { path = "../pp_lib" }
