name: Rust Personal Project

on: [workflow_dispatch]
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Check environment
      run: make version
    - name: Setup Rust environment and install Python dependencies
      run: |
        make \
          setup-rust-env \
          setup-python-dependencies
    - name: Lint (and format)
      run: make lint
    - name: Setup Docker network and services (Postgres, RabbitMQ)
      run: |
        make \
          create-docker-network \
          create-db-docker-volume \
          run-pp-storage \
          run-pp-queue
    - name: Check and configure Docker services (Postgres, RabbitMQ)
      run: |
        sleep 8
        make \
          docker-ps \
          test-pp-storage-connection \
          create-db \
          setup-pp-queue \
          docker-ps
    - name: Run Rust integration tests
      run: |
        make \
          db-test \
          queue-test
