name: Rust Personal Project

on: [workflow_dispatch]
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Check environment
      run: make version
    - name: Install Python dependencies
      run: make setup-python-dependencies
    - name: Setup Docker network and services (Postgres, RabbitMQ)
      run: |
        make \
          create-docker-network \
          create-db-docker-volume \
          run-pp-storage \
          test-pp-storage-connection \
          run-pp-queue \
          docker-ps
          
